### ISSUE TITLE
k0s: Additional control plane nodes doesn't join the cluster

### ISSUE THREAD

**Issue by DinaBelova** [Mirantis/hmc#156] opened 2024-08-06 20:02 UTC
Note: @a13x5 found it on version ```v1.28.2+k0s.0```, additional tests needed with a latest k0s version

Controller nodes are not joining the cluster after creation.

The machine objects are created normally, but stuck in the ```Provisioned``` state

```
NAME                      CLUSTER    NODENAME                                    PROVIDERID                              PHASE         AGE   VERSION
aws-cl-1-cp-0             aws-cl-1   ip-10-0-29-113.us-west-1.compute.internal   aws:///us-west-1b/i-02973850dfc3c1921   Running       31m   v1.28.2
aws-cl-1-cp-1             aws-cl-1                                               aws:///us-west-1b/i-075dd14506c4feb3b   Provisioned   31m   v1.28.2
aws-cl-1-cp-2             aws-cl-1                                               aws:///us-west-1b/i-0577a738d78a26e3f   Provisioned   31m   v1.28.2
aws-cl-1-md-9wgcp-kd2b4   aws-cl-1   ip-10-0-8-232.us-west-1.compute.internal    aws:///us-west-1b/i-0d6eeadf2ff13dc95   Running       31m
aws-cl-1-md-9wgcp-vm49k   aws-cl-1   ip-10-0-29-203.us-west-1.compute.internal   aws:///us-west-1b/i-04263668243885834   Running       31m
```

cloud-init provisioning works without problems and k0s get installed correctly, but k0scontroller service hangs:

```
root@ip-10-0-13-184:/home/ubuntu# systemctl status k0scontroller --no-pager --full
● k0scontroller.service - k0s - Zero Friction Kubernetes
     Loaded: loaded (/etc/systemd/system/k0scontroller.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-08-05 22:42:51 UTC; 12min ago
       Docs: https://docs.k0sproject.io
   Main PID: 1119 (k0s)
      Tasks: 8
     Memory: 19.0M
     CGroup: /system.slice/k0scontroller.service
             └─1119 /usr/local/bin/k0s controller --config=/etc/k0s.yaml --disable-components=konnectivity-server --enable-cloud-provider=true --enable-dynamic-config=true --enable-worker=true --kubelet-extra-args=--cloud-provider=external --hostname-override=ip-10-0-13-184.us-west-1.compute.internal --token-file=/etc/k0s.token

Aug 05 22:42:51 ip-10-0-13-184 systemd[1]: Started k0s - Zero Friction Kubernetes.
Aug 05 22:42:52 ip-10-0-13-184 k0s[1119]: time="2024-08-05 22:42:52" level=info msg="initialized join client successfully"
root@ip-10-0-13-184:/home/ubuntu# journalctl -u  k0scontroller
-- Logs begin at Mon 2024-08-05 22:42:15 UTC, end at Mon 2024-08-05 22:56:17 UTC. --
Aug 05 22:42:51 ip-10-0-13-184 systemd[1]: Started k0s - Zero Friction Kubernetes.
Aug 05 22:42:52 ip-10-0-13-184 k0s[1119]: time="2024-08-05 22:42:52" level=info msg="initialized join client successfully"
```

This is all logs from k0s controller, no other hints or errors. 

Behavior is the same in case of cluster creation from scratch with 3 nodes or in case of adding 2 nodes after.

No problems with scaling worker nodes observed.

**Comment by a13x5** [comment] 2024-08-07 20:56
Overlooked that this was already here((
Created #159 which is the same thing, but with known root cause.
Closing this as duplicate

**Closed by a13x5** 2024-08-07 20:56 UTC
Labels: bug
